### ISSUE TITLE
breaks against node-canvas

### ISSUE THREAD

**Issue by tomlarkworthy** [tmpvar/ctx-get-transform#1]
when setting a transform it says math not defined

```
ReferenceError: math is not defined
    at CanvasRenderingContext2d.tTransform [as transform] (/Users/larkworthy/dev/animaxe/node_modules/ctx-get-transform/ctx-get-transform.js:65:26)
    at CanvasRenderingContext2d.Context2d.setTransform (/Users/larkworthy/dev/animaxe/node_modules/canvas/lib/context2d.js:177:18)
    at CanvasRenderingContext2d.tSetTransform [as setTransform] (/Users/larkworthy/dev/animaxe/node_modules/ctx-get-transform/ctx-get-transform.js:78:27)
    at repl:1:6
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
```

**Comment by tmpvar** [comment]
closed by #2
